Notifiarr Updates
lidarr/Lidarr pull request #2222
Opened 2021-05-04 21:01 UTC by bakerboy448

#### Database Migration
YES - 46

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Todos
- [X] Tests
- N/A Wiki Updates

#### Issues Fixed or Closed by this PR

* Fixes #2221 
* Fixes #2130

2021-05-06 10:30 UTC, ta264 requested changes
Migration 46 is already in the plugins branch I'm afraid

2021-05-06 17:33 UTC, bakerboy448 commented
migration 47 it is;  @ta264 all set

2021-05-08 18:21 UTC, Qstick requested changes

2021-05-08 18:21 UTC, Qstick commented on src/NzbDrone.Core/Notifications/Notifiarr/NotifiarrSettings.cs.bak
> +using FluentValidation;
Kill this file

2021-05-08 21:25 UTC, Qstick approved these changes

2021-05-08 21:26 UTC, merged