Add ALAC 24bit
Lidarr/Lidarr pull request #3882
Opened 2023-07-17 01:41 UTC by jeffbyrnes

#### Database Migration

No

#### Description

Add an ALAC 24bit quality

#### Screenshot (if UI related)

#### Todos

- [ ] Tests
- [x] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #621

2023-07-17 01:54 UTC, Qstick requested changes
One additional comment. This also needs a new migration

2023-07-17 01:54 UTC, Qstick commented on src/NzbDrone.Core/Datastore/Migration/004_add_various_qualities_in_profile.cs
> +        ALAC_24,
Agree.. As well we shouldn't be making changes to this file. Qualities4 means this was the state of qualities at migration 4. Modifying old migrations isn't usually a great practice.

2023-07-17 01:55 UTC, jeffbyrnes commented on src/NzbDrone.Core/Datastore/Migration/004_add_various_qualities_in_profile.cs
> +        ALAC_24,
Fixed in 36f1cb1315

2023-07-17 01:58 UTC, jeffbyrnes commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +                    }
Definitely appreciate this suggestion, makes sense to me!

That said, just above is this snippet, and I was aiming to be consistent in style:

```c#
case Codec.FLAC:
    if (sampleSize == SampleSize.S24)
    {
        result.Quality = Quality.FLAC_24;
    }
    else
    {
        result.Quality = Quality.FLAC;
    }
```

2023-07-17 02:00 UTC, jeffbyrnes commented on src/NzbDrone.Core/Datastore/Migration/004_add_various_qualities_in_profile.cs
> +        ALAC_24,
@Qstick gotcha; I didn’t catch this is a migration! I’ll rework this. First time trying to make tweaks, and doing so blindly as someone who’s never worked with C# 🙂

2023-07-17 02:04 UTC, Qstick commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +                    }
Yes, let's change both. Thanks!

2023-07-17 02:07 UTC, Qstick commented
Migration 19 is a good example of what you'll need to do with the new migration.

2023-07-17 02:26 UTC, jeffbyrnes commented
Thanks @Qstick, I’ll use that as the basis for my new migration!

2023-07-17 02:35 UTC, jeffbyrnes commented
@Qstick, @mynameisbogdan, ok so I’m still flailing around pretty blindly, again, zero C# experience, but I’m familiar with code-based DB migrations (longtime Rubyist here, mostly used them via Ruby on Rails), so maybe ae478d3 is close?

2023-07-17 03:07 UTC, jeffbyrnes commented
Looks like things changed since migration 19, since this error is showing up all over: `no such table: Profiles`

I’ll poke around som more.

2023-07-18 00:04 UTC, jeffbyrnes commented
> Should be QualityProfiles. 

Ah! Thanks.

2023-07-18 01:32 UTC, jeffbyrnes commented
Looks like the build just timed out.

2023-07-18 14:14 UTC, jeffbyrnes commented
Sorry y’all, I’m not familiar enough to figure out what’s going on. Trying a build locally to see if that tells me more, but again, not a C# dev so very much stumbling around in the dark 😆

2023-07-22 00:34 UTC, Qstick commented
It's ok, stumbling in the dark is how we all learned c#. Take you time and feel free to ask questions here or discord

2023-07-24 15:22 UTC, jeffbyrnes commented
Hey thanks @mynameisbogdan, looks like all testing is passing with your help. I’ll look over what you changed compared to what I had so I can learn what I missed/did incorrectly.

2023-08-16 19:42 UTC, jeffbyrnes commented
Thanks @mynameisbogdan

2023-09-10 05:39 UTC, merged

2023-09-10 11:41 UTC, jeffbyrnes commented
Woohoo! Thanks for the help here y'all.

When will a new Docker image be baked that includes this?