mka support
Lidarr/Lidarr pull request #4361
Opened 2023-12-13 18:00 UTC by sharinganthief

#### Database Migration
YES - XXXX | NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Screenshot (if UI related)

#### Todos
- [ ] Tests
- [ ] Translation Keys (./src/NzbDrone.Core/Localization/Core/en.json)
- [ ] [Wiki Updates](https://wiki.servarr.com)

#### Issues Fixed or Closed by this PR

* Fixes #XXXX

2024-02-04 17:55 UTC, Qstick requested changes

2024-02-04 17:55 UTC, Qstick commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +        private static string StealCodecFromMatroskaTrack(AudioTrack matroskaCodec)
Move this `private` method below all the public interface methods.

2024-02-04 17:56 UTC, Qstick commented on src/NzbDrone.Core/Parser/QualityParser.cs
> +
Lint is failing on the multiple blank lines here

2025-02-08 01:18 UTC, bakerboy448 commented
PR abandoned

2025-02-08 01:18 UTC, closed without merging